localhost:
  local: true
  stage: dev
  composer_options: "install --prefer-dist --optimize-autoloader --no-progress --no-interaction --ignore-platform-reqs"

prod:
  hostname: 0.0.0.0
  user: change_me
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: prod
  deploy_path: /home/change_me/deploy_dir
  docker_config_path: /home/change_me/docker_config
  composer_options: "install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction --ignore-platform-reqs"
  domain: example.com.ua
